# Generated by Django 4.2.2 on 2023-07-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
